atom/language-shellscript

grammars/shell-unix-bash.cson
spec/shell-session-spec.coffee

This pull request fixes an issue reported in #7:
```bash
DEFAULT_BOOT_ARGS=${DEFAULT_BOOT_ARGS:-'root=${boot_fs} rw rootwait ${video}'}
DEVICE_MAP=($DEVICE_MAP)
DEFAULT_DTB=${DEFAULT_DTB:-"newest"}
```
See [fix in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-shellscript%2F29995b2ce14ec9c7e85cc22cc88853407595a5d1%2Fgrammars%2Fshell-unix-bash.cson&grammar_text=&code_source=from-text&code_url=&code=DEFAULT_BOOT_ARGS%3D%24{DEFAULT_BOOT_ARGS%3A-%27root%3D%24{boot_fs}+rw+rootwait+%24{video}%27}%0D%0ADEVICE_MAP%3D%28%24DEVICE_MAP%29%0D%0ADEFAULT_DTB%3D%24{DEFAULT_DTB%3A-%22newest%22}).

Variable constructs can include strings

---

grammars/shell-unix-bash.cson
spec/shell-session-spec.coffee

This pull request fixes an error reported in #5:
```bash
local r1=$(dd if=/dev/urandom bs=1)
ula_prefix="fd${r1}:${r2}:${r3}::/48"
```
See the [fix in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-shellscript%2Ffix-if-error%2Fgrammars%2Fshell-unix-bash.cson&grammar_text=&code_source=from-text&code_url=&code=local+r1%3D%24%28dd+if%3D%2Fdev%2Furandom+bs%3D1%29%0D%0Aula_prefix%3D%22fd%24{r1}%3A%24{r2}%3A%24{r3}%3A%3A%2F48%22).
~~The `if` keyword is still highlighted~~ but at least it doesn't break the highlighting of the code after it.

Fix error with if parameter of dd

---

grammars/shell-unix-bash.cson
spec/shell-session-spec.coffee

This pull request fixes the issue with here strings reported in #7:
```bash
lukkit_help() {
$cmd <<<'
lukkit patch build | Build patches from build/'
}
lukkit_patch(){
echo "Use: 'lukkit patch [apply|build]"
exit 1
}
```
See [fix in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-shellscript%2F9df628668e56fd41de2bd8655bcfa4651770ca54%2Fgrammars%2Fshell-unix-bash.cson&grammar_text=&code_source=from-text&code_url=&code=lukkit_help%28%29+{%0D%0A++++%24cmd+%3C%3C%3C%27%0D%0A++++lukkit+patch+build+|+Build+patches+from+build%2F%27%0D%0A}%0D%0A%0D%0Alukkit_patch%28%29{%0D%0A++++echo+%22Use%3A+%27lukkit+patch+[apply|build]%22%0D%0A++++exit+1%0D%0A}).
~~It loses `meta.herestring.shell` scopes …

Fix issue with herestrings

---

spec/shell-session-spec.coffee
spec/shell-unix-bash-spec.coffee

This PR almost halves the size of the specs file :arrow_down: :chart_with_downwards_trend:.
Changes:
* Separate `source.shell` tests into their own specs file, `shell-unix-bash-spec.coffee`
* No more `temporaryScopeHack`
* Test also for `source.shell`
* Use `tokenizeLines` only if necessary
* Combine (most of) the prompt tests into one test
* Combine two-line token assertions into one
Things to note:
* I couldn't also add the `>` test into the newly formed prompt test because it gets tokenized differently for some reason.  I'm pretty sure this is a bug and would like to get that fixed before this is merged for even more savings.

Combine and improve specs

---

grammars/shell-session.cson

This PR gets rid of the dedicated `>` prompt matcher and combines it with the other `[$#%]` one.  I don't really see a reason for `>` to be separated from the rest.
Alternatively, if there is in fact a good reason for this separation, another simple change so that the two matches tokenize identically would be to change the first regex to `^(>)\\s+(.*)$`.
Refs #16 which will test for this new behavior if it's merged (there's currently no way to test for this because of the `temporaryScopeHack` stuff).
(Also, L14 contains a null match.  Not sure if that's intended or not.)

Combine the two prompt matches

---

settings/language-shellscript.cson
spec/shell-unix-bash-spec.coffee

`if` and `elif` are always followed by the `then` keyword. In one
common coding style, the `then` keyword is often included on the same
line as the condition, following a semicolon:
```sh
if condition; then
...indented body...
fi
```
Alternatively, a newline can be used instead of a semicolon:
```sh
if condition
then
...indented body...
fi
```
This is similar to `while` and `until` loops, which can also be
written in both styles with the `do` keyword:
```sh
while condition; do
...indented body...
done
while condition
do
...indented body...
done
```
Prior to this commit, the increaseIndentPattern regular expression
supported both styles for `while` and `until` loops, which both use the
`do` keyword, but it only supported the semicolon style for `if` and
`elif`.
By replacing `if` and `elif` …

Increase indentation after `then` rather than `if` and `elif`.

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

In addition, this PR also tokenizes `in` as `keyword.control.shell` and fixes `done` being tokenized when preceded or followed by a dash or forward slash.
Fixes #31

Properly tokenize strings in for loops

---

grammars/shell-unix-bash.cson

This PR makes three improvements to the grammar's `firstLineMatch` pattern:
* **Extend the hashbang's list of interpreters to include `rc`**<br/>[`rc`](https://en.wikipedia.org/wiki/Rc) is the main command-line interpreter for the Version 10 and Plan 9 Unix systems, and is used in the header  of every shell-script written for those systems. More info [here](http://doc.cat-v.org/plan_9/4th_edition/papers/rc).<br/><br/>
* **Amend Emacs modeline to ignore capitalisation**<br/>Emacs reads the mode assignment case-insensitively, so something like `-*- Mode: Shell-script` would fail to match.<br/><br/>
* **Skip preceding whitespace before the `#` symbol**<br/>If the first line was intended, the pattern failed.

Improve firstLineMatch pattern

---

grammars/shell-unix-bash.cson

`.install` files (e.g., gvim.install for gVim) are used by PKGBUILDs to install peri-, post- and pre- installation checks and actions.

Adding install file ext

---

grammars/shell-unix-bash.cson

In this commit I am adding the zsh-theme file extension to the set of supported file types.

Adding zsh-theme ext

---

grammars/shell-unix-bash.cson

ebuilds are without exception best displayed with shell highlighting.
Addresses issue #48

added file type

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

This PR adds the battle-hardened modeline patterns tested at [Linguist](https://github.com/github/linguist/pull/3237), and also addresses a boundary-matching issue that causes the grammar to be falsely activated by `#!/bin/rubbi-sh`.

Revise modeline/hashbang-matching patterns

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

This PR makes a greedy variable capture in a for...in loop lazy to avoid scenarios like the following: `for variable in something do # hey look a comment with in`.  Prior to this change, the variable matching would keep matching until the last `in`, even if it was in a comment or totally irrelevant.
N/A
See above.
None.
Fixes #51

Fix greedy variable match in for loops

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

Cosmetic cleanups for the most part.
* Explicitly use `beginCaptures` and `endCaptures` when dealing with `begin` and `end` matches rather than using a `capture` to handle both.
* Remove captures that weren't doing anything.  I plan to return to heredocs and herestrings in the future to give them a proper makeover.
* Move `contentName` to below `name` where both exist.
* Unescape `{` and `}`.
* Remove unnecessary capturing groups.
* Fix herestrings not properly escaping spaces, leading `<<<ssssssssss'hi!'` to be tokenized as a valid herestring.  While …

Minor cleanups to grammar source

---

snippets/language-shellscript.cson

This fixes a very annoying behavior where Atom suggests me function (because it contains f and i) when I type fi to close an if statement.
This fix adds a `fi` snippet that just does fi so that users can type fi to get fi and type more letters of function to get function.
remove the function snippet altogether
usability. I never use the function snippet but I type fi about 100 times per day. Each time I need to be careful not to press ENTER but ESCAPE to abort the snippet suggestion.
none that I can think of.
I did not create an issue because the fix is so obvious that I thought to just contribute it :-)

Stop suggesting function for fi

---

grammars/shell-unix-bash.cson

Depending on the regular expression engine used, \h does not always
mean the same. With a PCRE engine, it matches white spaces, whereas,
with a Oniguruma engine, it matches hexademical digit characters.
Atom uses an Oniguruma engine, but github.com relies on a PCRE
engine.
None were considered.
Makes the grammar PCRE-compatible, so that it can be used on github.com.
I don't have any way to check these PCRE vs. Oniguruma discrepancies at the moment. I'm working on a new test at the Linguist-level to check for all known discrepancies.

Avoid using the ambiguous \h shorthand character

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

Spaces are allowed before the heredoc identifier, so recognize them.
Fixes atom/atom#15397

Allow spaces before heredoc identifier

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

Two issues have been fixed with this PR.  The first one is that for language-specific heredocs, there was no boundary checking being performed.  Which meant that `<<SHELLOILCOMPANY` caused the heredoc to be tokenized as Shell.  The second one was that generic heredocs were _too_ strict with the valid identifier regex, only allowing word characters.  It now uses a negative character class against `;`, `&`, `<`, and whitespace.
The spec which was supposed to catch the first issue was broken and is fixed in this PR.
Fixes #71

Properly delimit heredoc identifiers

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

A classic switcheroo.  Further follow-ups could include investigating whether or not the boundary checks for `function-definition` can be tightened, but this PR shouldn't cause anything to regress.
Fixes #70
Fixes #73

Give strings priority over functions

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

There can be spaces between the herestring token and identifier.
N/A
Proper herestring highlighting.
N/A
Fixes #82

Tokenize unquoted herestrings properly

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

`)` cannot be a part of a `word`, therefore do not treat it as one in herestrings.
None.
Herestrings that are ended by parentheses will be tokenized correctly.
None.
Fixes #90

End herestrings when parentheses are reached

---

grammars/tree-sitter-bash.cson
package.json

⚠️ Work In Progress ⚠️
This adds an alternative Bash grammar that uses [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash) for parsing instead of [first-mate](https://github.com/atom/first-mate).

Add tree-sitter Bash grammar

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

Heredocs can contain leading spaces after the `<<`.  Recognize them when the heredoc itself is also quoted.
None.
Spaces before a quoted heredoc identifier should now work.
None.
Fixes #103

Tokenize heredocs with leading spaces

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

https://www.gnu.org/software/bash/manual/html_node/Comments.html states that `#` only starts comments if it starts a word.  While this isn't strictly true (e.g. `# hello` is a comment) that still rules out `-#` as a comment.  Therefore add a lookbehind to make sure a dash does not precede a possible comment.
Refactor comment regex to try to match the above reference better.
The curl `-#` argument should no longer make the rest of the line a comment.
I don't really see any.
Fixes #104

Do not tokenize -# as a comment in argument lists

---

package.json

tree-sitter-bash@0.13.9 introduces a fix for Tree-sitter users experiencing the issue described in https://github.com/atom/language-shellscript/issues/139. (If you're not using Tree-sitter, and you're instead using the old Textmate grammar, you'll still see the issue.)
----
*List of changes between `tree-sitter-bash@0.13.8` and `tree-sitter-bash@0.13.9`: https://github.com/tree-sitter/tree-sitter-bash/compare/v0.13.8...v0.13.9*

⬆️ tree-sitter-bash@0.13.9

---

grammars/tree-sitter-bash.cson
package.json

Fixes #146
Depends on https://github.com/tree-sitter/tree-sitter-bash/pull/54, which also contains more information.

Support ANSII-C escaped strings in Bash

---

grammars/shell-unix-bash.cson
spec/shell-unix-bash-spec.coffee

Add support for recognizing expansions in heredocs. The `begin` regexes of the existing rules are modified to not match the expanded form (which doesn't have quotes, see [here](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07_04)). New rules for the expanded form are added that are identical to the existing ones minus the quotes. The `patterns` are taken from `'string'` (minus the quotes).
None
Variables in shell script heredocs will be correctly highlighted.
None
#151

Fix heredoc expansion
